#!/usr/bin/env python3
"""Regenerate the provider-level index files providers/index/<provider>-<ver>.txt
from providers/schemas/*.schema.json (tofu providers schema -json output).

Emits resources, data sources and ephemeral resources, so a provider's
ephemeral resources (which keep secrets out of state) are never hidden.
Per-resource flattened files (proxmox_virtual_environment_*.txt) are not touched.
"""
import json, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
for sch in sorted((root / "providers/schemas").glob("*.schema.json")):
    name = sch.name[: -len(".schema.json")]
    data = json.loads(sch.read_text())
    for addr, p in data.items():
        ver = name.rsplit("-", 1)[1]
        res = sorted(p.get("resource_schemas", {}))
        ds = sorted(p.get("data_source_schemas", {}))
        eph = sorted(p.get("ephemeral_resource_schemas", {}))
        out = [f"# {addr} {ver}: {len(res)} resources, {len(ds)} data sources, "
               f"{len(eph)} ephemeral resources. Generated by tofu providers schema -json. Do not edit.",
               "# resources", *res, "", "# data sources", *ds, "",
               "# ephemeral resources", *eph]
        (root / "providers/index" / f"{name}.txt").write_text("\n".join(out) + "\n")
        print(f"{name}: {len(res)}/{len(ds)}/{len(eph)}", file=sys.stderr)
